# docker-compose.yml - Versión completamente parametrizada y segura
version: '3.8'

services:
  # Servicio de la Base de Datos MySQL
  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: ${DB_CONTAINER_NAME:-annyamodas-db}
    restart: ${RESTART_POLICY:-always}
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
      MYSQL_COLLATION: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}
    ports:
      - '${DB_HOST_IP:-127.0.0.1}:${DB_PORT:-3306}:3306'
    volumes:
      - ${DB_DATA_VOLUME:-mysql-data}:/var/lib/mysql
      - ${INIT_SQL_PATH:-./init.sql}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ${NETWORK_NAME:-annyamodas-network}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: ${DB_HEALTH_TIMEOUT:-20s}
      retries: ${DB_HEALTH_RETRIES:-10}

  # Servicio de la Aplicación Next.js
  app:
    build: 
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${DOCKERFILE_PATH:-Dockerfile}
    container_name: ${APP_CONTAINER_NAME:-annyamodas-app}
    restart: ${RESTART_POLICY:-always}
    ports:
      - '${APP_HOST_IP:-0.0.0.0}:${APP_PORT:-8080}:${APP_INTERNAL_PORT:-3000}'
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      # Configuración de aplicación
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${APP_INTERNAL_PORT:-3000}
      HOSTNAME: ${APP_HOSTNAME:-0.0.0.0}
      
      # Base de datos
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      
      # Seguridad
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
      # Configuración de uploads
      CONTENT_DIR: ${CONTENT_DIR_CONTAINER:-/opt/annyamodas/CONTENT}
      UPLOADS_DIR: ${UPLOADS_DIR_CONTAINER:-/opt/annyamodas/CONTENT/uploads}
      UPLOAD_DIR: ${UPLOADS_DIR_CONTAINER:-/opt/annyamodas/CONTENT/uploads}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-5242880}
      ALLOWED_FILE_TYPES: ${ALLOWED_FILE_TYPES:-image/jpeg,image/png,image/webp,image/gif}
      
      # Configuración de cache
      UPLOADS_NO_CACHE: ${UPLOADS_NO_CACHE:-true}
      NEXT_CACHE_ENABLED: ${NEXT_CACHE_ENABLED:-false}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-1}
      
      # Configuración de proxy/headers
      TRUST_PROXY: ${TRUST_PROXY:-true}
      FORWARDED_HEADERS: ${FORWARDED_HEADERS:-true}
      
      # Debug (solo desarrollo)
      DEBUG_PROTOCOL_DETECTION: ${DEBUG_PROTOCOL_DETECTION:-false}
      DEBUG_UPLOADS: ${DEBUG_UPLOADS:-false}
      
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ${NETWORK_NAME:-annyamodas-network}
    
    # Volúmenes parametrizados
    volumes:
      - ${CONTENT_DIR_HOST}:${CONTENT_DIR_CONTAINER:-/opt/annyamodas/CONTENT}
      
    # Usuario parametrizado
    user: "${APP_USER_ID:-1001}:${APP_GROUP_ID:-1001}"

# Definición de volúmenes y redes
volumes:
  mysql-data:
    driver: ${VOLUME_DRIVER:-local}

networks:
  annyamodas-network:
    driver: ${NETWORK_DRIVER:-bridge}