# docker-compose.yml
version: '3.8'

services:
  # Servicio de la Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: annyamodas-db
    restart: always
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --innodb-flush-log-at-trx-commit=0
    environment:
      CONTENT_DIR: ${CONTENT_DIR:-/home/womx/CONTENT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-1322655cf8ca7aaf2d57e428f4a07a366ce0384882d73f60d990832d05860967}
      MYSQL_DATABASE: ${DATABASE_NAME:-annyamodas_db}
      MYSQL_USER: ${DATABASE_USER:-annyamodas_user}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-5eba7d39cfb}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      # Exponemos el puerto de MySQL solo a nuestra máquina local para seguridad
      - '127.0.0.1:3306:3306'
    volumes:
      # Persiste los datos de la base de datos
      - mysql-data:/var/lib/mysql
      # Script de inicialización
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - annyamodas-network
    # Verificación de salud de la base de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Servicio de la Aplicación Next.js
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: annyamodas-app
    restart: always
    ports:
      - '${APP_PORT:-8080}:3000'
    # ✅ Usar archivo .env específicamente
    env_file:
      - .env
    environment:
      # ✅ Sobrescribir variables específicas para el contenedor
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_HOST: db  # Siempre será 'db' dentro de Docker
      DATABASE_USER: ${DATABASE_USER:-annyamodas_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-5eba7d39cfb}
      DATABASE_NAME: ${DATABASE_NAME:-annyamodas_db}
      JWT_SECRET: ${JWT_SECRET:-ea66f306553403a756d86c7b20f6712b4e4f05c8d4f4c801a0912f01ca5cf473}
      # Variables para subida de imágenes
      UPLOAD_DIR: /app/public/uploads
    depends_on:
      db:
        condition: service_healthy # Espera a que MySQL esté ready
    networks:
      - annyamodas-network
    # Volumen para uploads
    volumes:
      - /home/womx/annyamodas/CONTENT:/home/womx/annyamodas/CONTENT

# Definición de volúmenes y redes
volumes:
  mysql-data:
    driver: local

networks:
  annyamodas-network:
    driver: bridge